services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/travel  # Connect to local MongoDB
      - JWT_SECRET=your_jwt_secret_here
